import {chromium} from 'playwright';
import {readFile,mkdir} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
import {config} from 'dotenv';
import pg from 'pg';
config({quiet:true});const url=new URL(process.env.DATABASE_URL);if(url.hostname!=='127.0.0.1'||url.port!=='55433'||url.pathname!=='/thinthai_dev')throw Error('Local only');const db=new pg.Pool({connectionString:url.href});const credentials=await readFile('.local/dev-accounts.md','utf8');const account=role=>credentials.split('\n').find(s=>s.startsWith('| '+role+' |')).split('|').map(s=>s.trim()).slice(2,4);
const browser=await chromium.launch({headless:true,channel:'chrome'});let storeId;const name='สินค้าสั่งซื้อ '+randomUUID().slice(0,8);
async function login(page,role){const [email,password]=account(role);await page.goto('http://127.0.0.1:3200/workspace');await page.getByLabel('อีเมล',{exact:true}).fill(email);await page.getByLabel('รหัสผ่าน',{exact:true}).fill(password);await page.getByRole('button',{name:'เข้าสู่ระบบ',exact:true}).click();await page.getByRole('button',{name:'คำสั่งซื้อ',exact:true}).waitFor();}
try{await mkdir('design/previews/orders',{recursive:true});const buyer=await browser.newPage(),merchant=await browser.newPage();const errors=[];for(const page of [buyer,merchant])page.on('pageerror',e=>errors.push(e.message));await login(buyer,'USER');await login(merchant,'MERCHANT');const headers={Origin:'http://127.0.0.1:3200','X-ThinThai-Action':'1'};
let res=await merchant.request.post('http://127.0.0.1:3200/api/v1/stores',{headers,data:{name:'ร้าน '+name,address:'ที่อยู่ทดสอบ',category:'craft',subdistrictId:'500107',lat:null,lng:null,active:true}});assert.equal(res.status(),201);storeId=(await res.json()).id;
res=await merchant.request.post('http://127.0.0.1:3200/api/v1/stores/'+storeId+'/products',{headers,data:{name,description:'สำหรับทดสอบคำสั่งซื้อ',category:'craft',fulfillment:'pickup',priceSatang:12550,active:true,initialStock:10}});assert.equal(res.status(),201);
for(const [device,width,height] of [['desktop',1440,1000],['tablet',820,1180],['mobile',390,844]]){
 await buyer.setViewportSize({width,height});await buyer.goto('http://127.0.0.1:3200/catalog');const card=buyer.locator('.product-card').filter({has:buyer.getByRole('heading',{name,exact:true})});await card.getByRole('button',{name:'เพิ่มลงตะกร้า'}).click();const cart=buyer.locator('.cart-panel');await cart.getByLabel('จำนวน '+name,{exact:true}).fill('2');await cart.getByLabel('ชื่อผู้รับ').fill('ผู้ซื้อทดสอบ');await cart.getByLabel('เบอร์ผู้รับ').fill('0812345678');assert.equal(await buyer.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await buyer.screenshot({path:`design/previews/orders/${device}-cart.png`,fullPage:true});
 await cart.getByRole('button',{name:'ยืนยันคำสั่งซื้อทดลอง'}).click();await buyer.getByRole('status').filter({hasText:'บันทึกคำสั่งซื้อ'}).waitFor();await buyer.getByRole('link',{name:'ดูคำสั่งซื้อ',exact:true}).click();const buyerOrder=buyer.locator('.order-card').filter({hasText:name}).first();await buyerOrder.getByText('รอร้านรับรายการ',{exact:true}).waitFor();
 if(device==='desktop'){await buyerOrder.getByRole('button',{name:'ยกเลิกรายการ',exact:true}).click();await buyer.getByLabel('เหตุผลการเปลี่ยนสถานะ').fill('ผู้ซื้อยกเลิกทดสอบ');await buyer.getByRole('button',{name:'ยืนยันสถานะ'}).click();await buyerOrder.getByText('ลูกค้ายกเลิก',{exact:true}).first().waitFor();}
 else{await merchant.reload();await merchant.getByRole('button',{name:'คำสั่งซื้อ',exact:true}).click();await merchant.getByLabel('มุมมองคำสั่งซื้อ').selectOption('shop');const shopOrder=merchant.locator('.order-card').filter({hasText:name}).first();await shopOrder.getByText('รอร้านรับรายการ',{exact:true}).waitFor();await shopOrder.getByRole('button',{name:device==='tablet'?'ปฏิเสธรายการ':'รับรายการ',exact:true}).click();await merchant.getByLabel('เหตุผลการเปลี่ยนสถานะ').fill('ร้านดำเนินการทดสอบ');await merchant.getByRole('button',{name:'ยืนยันสถานะ'}).click();if(device==='mobile'){await shopOrder.getByRole('button',{name:'ทำรายการเสร็จสิ้น'}).click();await merchant.getByLabel('เหตุผลการเปลี่ยนสถานะ').fill('รับสินค้าที่ร้านแล้ว');await merchant.getByRole('button',{name:'ยืนยันสถานะ'}).click();await shopOrder.getByText('เสร็จสิ้น',{exact:true}).first().waitFor();}else await shopOrder.getByText('ร้านปฏิเสธ',{exact:true}).first().waitFor();await buyer.reload();await buyerOrder.getByText(device==='tablet'?'ร้านปฏิเสธ':'เสร็จสิ้น',{exact:true}).first().waitFor();}
 await buyer.screenshot({path:`design/previews/orders/${device}-orders.png`,fullPage:true});console.log(device+' cart / checkout / order status passed');
}assert.deepEqual(errors,[]);const stock=(await db.query('SELECT stock,reserved FROM products WHERE store_id=$1',[storeId])).rows[0];assert.deepEqual(stock,{stock:8,reserved:0});console.log('Stock restored for cancellation/rejection; completed order consumed exactly 2 units.');
}finally{await browser.close();if(storeId){await db.query('DELETE FROM orders WHERE store_id=$1',[storeId]);await db.query('DELETE FROM store_memberships WHERE store_id=$1',[storeId]);await db.query('DELETE FROM stores WHERE id=$1',[storeId]);}await db.end();}
