"use client";
import {useEffect,useState} from 'react';
type Application={id:string;name:string;category:string;address:string;phone:string;subdistrictId:string;provinceId:string;districtId:string;province:string;district:string;subdistrict:string;applicant:string;status:string;version:number;reason:string;storeId:string|null};
type Area={id:string;name:string;districtId:string;district:string;provinceId:string;province:string};
const labels:Record<string,string>={draft:'ฉบับร่าง',submitted:'รอตรวจ',changes_requested:'ขอแก้ไข',approved:'อนุมัติ',rejected:'ไม่อนุมัติ',edited:'แก้ไขข้อมูล'};
async function api(path:string,body?:unknown){const response=await fetch('/api/v1/'+path,{cache:'no-store',...(body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-ThinThai-Action':'1'},body:JSON.stringify(body)})});const data=await response.json();if(!response.ok)throw Error(data.message??'ทำรายการไม่สำเร็จ');return data;}
export default function ApplicationsPanel({review,onRefresh}:{review:boolean;onRefresh:()=>void}){
 const [rows,setRows]=useState<Application[]>([]),[areas,setAreas]=useState<Area[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true);
 const [editing,setEditing]=useState<Application|null|undefined>(undefined),[name,setName]=useState(''),[category,setCategory]=useState('food'),[address,setAddress]=useState(''),[phone,setPhone]=useState(''),[province,setProvince]=useState(''),[district,setDistrict]=useState(''),[subdistrict,setSubdistrict]=useState('');
 const [selected,setSelected]=useState<Application|null>(null),[decision,setDecision]=useState('changes_requested'),[reason,setReason]=useState(''),[history,setHistory]=useState<{event:string;reason:string;actor:string;createdAt:string}[]|null>(null);
 async function load(){const [items,places]=await Promise.all([api(review?'applications/review':'applications'),review?Promise.resolve([]):api('applications/areas')]);setRows(items);setAreas(places);}
 useEffect(()=>{setLoading(true);void load().catch(e=>setError(e.message)).finally(()=>setLoading(false));},[review]);
 function edit(a:Application|null){setEditing(a);setName(a?.name??'');setCategory(a?.category??'food');setAddress(a?.address??'');setPhone(a?.phone??'');setProvince(a?.provinceId??'');setDistrict(a?.districtId??'');setSubdistrict(a?.subdistrictId??'');setError('');setNotice('');setHistory(null);}
 async function action(work:()=>Promise<unknown>,message:string){setBusy(true);setError('');setNotice('');try{await work();setEditing(undefined);setSelected(null);setHistory(null);await load();setNotice(message);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function save(e:React.FormEvent){e.preventDefault();await action(()=>api(editing?'applications/'+editing.id:'applications',{name,category,address,phone,subdistrictId:subdistrict,...(editing?{version:editing.version}:{})}),'บันทึกแล้ว กรุณากดส่งตรวจเมื่อข้อมูลพร้อม');}
 async function showHistory(id:string){setBusy(true);setError('');try{setHistory(await api('applications/'+id+'/history'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const provinces=[...new Map(areas.map(a=>[a.provinceId,a.province])).entries()],districts=[...new Map(areas.filter(a=>a.provinceId===province).map(a=>[a.districtId,a.district])).entries()];
 return <section className="panel application-panel"><div className="panel-head"><div><h2>{review?'ตรวจคำขอเปิดร้าน':'สมัครผู้ประกอบการ'}</h2><p>{review?'ตรวจข้อมูลตามพื้นที่รับผิดชอบ อนุมัติแล้วจึงสร้างร้านและมอบสิทธิ์':'บันทึกข้อมูลร้าน → ส่งตรวจ → ติดตามผล → เริ่มจัดการร้าน'}</p></div><button className="outline" disabled={busy} onClick={()=>action(load,'โหลดข้อมูลล่าสุดแล้ว')}>โหลดข้อมูลล่าสุด</button></div><p className="notice">ระยะนี้รับข้อมูลร้านและช่องทางติดต่อ ยังไม่รองรับแนบเอกสารหรือยืนยันตัวตนทางกฎหมาย พื้นที่เป็นชุดตัวอย่าง</p>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="success">{notice}</p>}{loading?<p role="status">กำลังโหลดคำขอ…</p>:<>{!review&&editing===undefined&&!rows.some(a=>['draft','submitted','changes_requested'].includes(a.status))&&<button className="apply-new" disabled={busy} onClick={()=>edit(null)}>ยื่นคำขอเปิดร้าน</button>}{editing!==undefined&&<form className="application-form" onSubmit={save}><h3>{editing?'แก้ไขคำขอ':'ข้อมูลร้านที่ต้องการเปิด'}</h3><fieldset disabled={busy} className="editor-fields"><div className="form-grid"><label>ชื่อร้าน<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>หมวดร้าน<select aria-label="หมวดร้าน" value={category} onChange={e=>setCategory(e.target.value)}><option value="food">อาหาร</option><option value="craft">สินค้าชุมชน</option></select></label><label>จังหวัด<select aria-label="จังหวัด" required value={province} onChange={e=>{setProvince(e.target.value);setDistrict('');setSubdistrict('');}}><option value="">เลือกจังหวัด</option>{provinces.map(([id,n])=><option value={id} key={id}>{n}</option>)}</select></label><label>อำเภอ / เขต<select aria-label="อำเภอ / เขต" required value={district} onChange={e=>{setDistrict(e.target.value);setSubdistrict('');}}><option value="">เลือกอำเภอ</option>{districts.map(([id,n])=><option value={id} key={id}>{n}</option>)}</select></label><label>ตำบล / แขวง<select aria-label="ตำบล / แขวง" required value={subdistrict} onChange={e=>setSubdistrict(e.target.value)}><option value="">เลือกตำบล</option>{areas.filter(a=>a.districtId===district).map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label><label>เบอร์ติดต่อ<input type="tel" required minLength={8} maxLength={20} autoComplete="tel" value={phone} onChange={e=>setPhone(e.target.value)}/></label></div><label>ที่อยู่ร้าน<textarea required minLength={5} maxLength={500} value={address} onChange={e=>setAddress(e.target.value)}/></label><p>ข้อมูลนี้ใช้ประกอบการตรวจคำขอโดยผู้ดูแลพื้นที่ ยังไม่เผยแพร่เป็นหน้าร้าน</p><div className="editor-actions"><button>บันทึกฉบับร่าง</button><button type="button" className="outline" onClick={()=>setEditing(undefined)}>ยกเลิก</button></div></fieldset></form>}
 {rows.length===0&&editing===undefined&&<p className="empty">ยังไม่มีคำขอ</p>}<div className="application-list">{rows.map(a=><article className="application-card" key={a.id}><div className="panel-head"><h3>{a.name}</h3><span className="badge">{labels[a.status]}</span></div><p>{a.applicant} · {a.category==='food'?'อาหาร':'สินค้าชุมชน'}</p><p>{a.province} / {a.district} / {a.subdistrict}</p><p>{a.address} · ติดต่อ {a.phone}</p>{a.reason&&<p className="review-reason">เหตุผลจากผู้ดูแล: {a.reason}</p>}<div className="store-actions">{!review&&['draft','changes_requested'].includes(a.status)&&<><button disabled={busy} className="outline" onClick={()=>edit(a)}>แก้ไขคำขอ</button><button disabled={busy} onClick={()=>action(()=>api('applications/'+a.id+'/submit',{version:a.version}),'ส่งคำขอแล้ว รอผู้ดูแลตรวจสอบ')}>ส่งตรวจ</button></>}{review&&a.status==='submitted'&&<button disabled={busy} onClick={()=>{setSelected(a);setReason('');setDecision('changes_requested');}}>ตรวจคำขอ</button>}{!review&&a.status==='approved'&&<button disabled={busy} onClick={onRefresh}>อัปเดตสิทธิ์เพื่อจัดการร้าน</button>}<button className="outline" disabled={busy} onClick={()=>showHistory(a.id)}>ประวัติคำขอ</button></div></article>)}</div>
 {selected&&<form className="review-form auth-form" onSubmit={e=>{e.preventDefault();void action(()=>api('applications/'+selected.id+'/review',{version:selected.version,decision,reason}),'บันทึกผลตรวจแล้ว');}}><h3>ผลตรวจ: {selected.name}</h3><label>ผลการตรวจ<select aria-label="ผลการตรวจ" disabled={busy} value={decision} onChange={e=>setDecision(e.target.value)}><option value="changes_requested">ขอแก้ไข</option><option value="approved">อนุมัติ</option><option value="rejected">ไม่อนุมัติ</option></select></label><label>เหตุผล<textarea disabled={busy} required minLength={5} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label>{decision==='approved'&&<p>จะสร้างร้านในสถานะพักร้านและมอบสิทธิ์ให้ผู้สมัคร ต้องปักหมุดและตั้งค่าร้านก่อนเริ่มใช้งาน</p>}<button disabled={busy}>ยืนยันผลตรวจ</button><button disabled={busy} type="button" className="outline" onClick={()=>setSelected(null)}>ยกเลิกการตรวจ</button></form>}{history&&<section className="application-history"><h3>ประวัติคำขอ</h3>{history.map((h,i)=><p key={i}>{labels[h.event]??h.event} · {h.actor} · {new Date(h.createdAt).toLocaleString('th-TH')} {h.reason&&'— '+h.reason}</p>)}</section>}</>}</section>;
}
