import {Inject,Injectable,ForbiddenException,BadRequestException,ConflictException,NotFoundException} from '@nestjs/common';
import {randomUUID} from 'node:crypto';
import type {PoolClient} from 'pg';
import sharp from 'sharp';
import {z} from 'zod';
import {Db} from './db';
import {canManage,type Actor} from './access';
import {distanceKm} from './store-input';
const fields={name:z.string().trim().min(1).max(120),description:z.string().trim().max(2000),category:z.enum(['food','craft']),fulfillment:z.enum(['instant_food_delivery','parcel_delivery','pickup']),priceSatang:z.number().int().min(1).max(100000000),active:z.boolean()};
export const productCreate=z.object({...fields,initialStock:z.number().int().min(0).max(1000000)}).strict();
export const productEdit=z.object({...fields,version:z.number().int().positive()}).strict();
export const stockInput=z.object({version:z.number().int().positive(),delta:z.number().int().min(-1000000).max(1000000).refine(v=>v!==0),reason:z.string().trim().min(3).max(300),requestKey:z.uuid()}).strict();
export const imageInput=z.object({version:z.number().int().positive(),data:z.string().min(4).max(2800000).nullable()}).strict();
const columns=`p.id,p.store_id AS "storeId",p.name,p.description,p.category,p.fulfillment,p.price_satang AS "priceSatang",p.stock,p.reserved,p.active,p.version,(p.image_data IS NOT NULL) AS "hasImage"`;
const visible=`p.active AND p.stock>0 AND s.active AND (p.fulfillment<>'instant_food_delivery' OR (s.category='food' AND s.delivery_enabled AND s.latitude IS NOT NULL AND s.longitude IS NOT NULL))`;
@Injectable() export class Products {
 constructor(@Inject(Db) private readonly db:Db){}
 private async store(c:PoolClient,a:Actor,id:string){const row=(await c.query('SELECT s.id,s.category,t.province_id AS "provinceId" FROM stores s JOIN subdistricts t ON t.id=s.subdistrict_id WHERE s.id=$1 FOR UPDATE OF s',[id])).rows[0];if(!row||!canManage(a,row))throw new ForbiddenException();return row;}
 private async locked(c:PoolClient,a:Actor,id:string){const ref=(await c.query('SELECT store_id FROM products WHERE id=$1',[id])).rows[0];if(!ref)throw new ForbiddenException();const store=await this.store(c,a,ref.store_id);const p=(await c.query(`SELECT ${columns} FROM products p WHERE p.id=$1 FOR UPDATE`,[id])).rows[0];return {p,store};}
 private version(p:{version:number},version:number){if(p.version!==version)throw new ConflictException('ข้อมูลสินค้าถูกแก้ไขแล้ว กรุณาโหลดข้อมูลล่าสุด');}
 private fulfillment(v:{category:string;fulfillment:string},store:{category:string}){if(v.fulfillment==='instant_food_delivery'&&(v.category!=='food'||store.category!=='food'))throw new BadRequestException('ส่งอาหารทันทีใช้ได้เฉพาะสินค้าอาหารในร้านอาหาร');}
 private async log(c:PoolClient,a:Actor,id:string,event:string,reason:string,before:unknown,delta:number|null=null,key:string|null=null){const after=(await c.query(`SELECT ${columns} FROM products p WHERE p.id=$1`,[id])).rows[0];await c.query('INSERT INTO product_history(id,product_id,actor_id,event,reason,delta,request_key,before_data,after_data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[randomUUID(),id,a.id,event,reason,delta,key,before,after]);return after;}
 async list(a:Actor,storeId:string){return this.db.transaction(async c=>{await this.store(c,a,storeId);return (await c.query(`SELECT ${columns} FROM products p WHERE p.store_id=$1 ORDER BY p.created_at DESC LIMIT 200`,[storeId])).rows;});}
 async create(a:Actor,storeId:string,v:z.infer<typeof productCreate>){return this.db.transaction(async c=>{const store=await this.store(c,a,storeId);this.fulfillment(v,store);const id=randomUUID();await c.query('INSERT INTO products(id,store_id,name,description,category,fulfillment,price_satang,stock,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[id,storeId,v.name,v.description,v.category,v.fulfillment,v.priceSatang,v.initialStock,v.active]);return this.log(c,a,id,'created','สต๊อกเริ่มต้น',null,v.initialStock);});}
 async edit(a:Actor,id:string,v:z.infer<typeof productEdit>){return this.db.transaction(async c=>{const {p,store}=await this.locked(c,a,id);this.version(p,v.version);this.fulfillment(v,store);await c.query('UPDATE products SET name=$1,description=$2,category=$3,fulfillment=$4,price_satang=$5,active=$6,version=version+1,updated_at=now() WHERE id=$7',[v.name,v.description,v.category,v.fulfillment,v.priceSatang,v.active,id]);return this.log(c,a,id,'updated','แก้ไขสินค้า',p);});}
 async stock(a:Actor,id:string,v:z.infer<typeof stockInput>){return this.db.transaction(async c=>{const {p}=await this.locked(c,a,id);const old=(await c.query('SELECT actor_id,delta,reason,after_data FROM product_history WHERE product_id=$1 AND request_key=$2',[id,v.requestKey])).rows[0];if(old){if(old.actor_id!==a.id||old.delta!==v.delta||old.reason!==v.reason)throw new ConflictException('รหัสรายการนี้ใช้กับข้อมูลอื่นแล้ว');return {...p,replayed:true};}this.version(p,v.version);if(p.stock+v.delta<0||p.stock+p.reserved+v.delta>1000000)throw new BadRequestException('สต๊อกพร้อมขายต้องไม่ติดลบ และรวมยอดจองต้องไม่เกิน 1,000,000');await c.query('UPDATE products SET stock=stock+$1,version=version+1,updated_at=now() WHERE id=$2',[v.delta,id]);return this.log(c,a,id,'stock',v.reason,p,v.delta,v.requestKey);});}
 async upload(a:Actor,id:string,v:z.infer<typeof imageInput>){await this.db.transaction(async c=>{const {p}=await this.locked(c,a,id);this.version(p,v.version);});let bytes:Buffer|null=null;
 if(v.data!==null){try{if(!/^[A-Za-z0-9+/]+={0,2}$/.test(v.data)||v.data.length%4!==0)throw Error();const input=Buffer.from(v.data,'base64');if(input.length>2*1024*1024)throw Error();const image=sharp(input,{limitInputPixels:16000000,failOn:'warning'});const meta=await image.metadata();if(!['jpeg','png','webp'].includes(meta.format??'')||(meta.pages??1)!==1)throw Error();bytes=await image.rotate().resize({width:1200,height:1200,fit:'inside',withoutEnlargement:true}).webp({quality:82}).toBuffer();if(bytes.length>1048576)throw Error();}catch{throw new BadRequestException('ใช้รูป JPG, PNG หรือ WebP ไม่เกิน 2 MB และ 16 ล้านพิกเซล ไม่รับภาพเคลื่อนไหว');}}
 return this.db.transaction(async c=>{const {p}=await this.locked(c,a,id);this.version(p,v.version);await c.query('UPDATE products SET image_data=$1,version=version+1,updated_at=now() WHERE id=$2',[bytes,id]);return this.log(c,a,id,'image',bytes?'เปลี่ยนรูปสินค้า':'ลบรูปสินค้า',p);});}
 async image(id:string,a?:Actor){const row=(await this.db.pool.query(`SELECT p.image_data,(${visible}) AS visible,s.id,t.province_id AS "provinceId" FROM products p JOIN stores s ON s.id=p.store_id JOIN subdistricts t ON t.id=s.subdistrict_id WHERE p.id=$1`,[id])).rows[0];if(!row?.image_data||(!row.visible&&(!a||!canManage(a,row))))throw new NotFoundException();return row.image_data as Buffer;}
 async history(a:Actor,id:string){return this.db.transaction(async c=>{await this.locked(c,a,id);return (await c.query('SELECT h.event,h.reason,h.delta,h.created_at AS "createdAt",h.after_data AS after,u.display_name AS actor FROM product_history h JOIN app_users u ON u.id=h.actor_id WHERE product_id=$1 ORDER BY h.created_at DESC LIMIT 50',[id])).rows;});}
 async catalog(){return (await this.db.pool.query(`SELECT ${columns},s.name AS "storeName" FROM products p JOIN stores s ON s.id=p.store_id WHERE ${visible} ORDER BY p.created_at DESC LIMIT 200`)).rows;}
 async availability(id:string,point?:{lat:number;lng:number}){const row=(await this.db.pool.query(`SELECT p.fulfillment,s.latitude::float8 AS lat,s.longitude::float8 AS lng,s.delivery_radius_km::float8 AS radius FROM products p JOIN stores s ON s.id=p.store_id WHERE p.id=$1 AND ${visible}`,[id])).rows[0];if(!row)throw new NotFoundException();if(row.fulfillment!=='instant_food_delivery')return {eligible:true,reason:'ไม่ใช้โซนจัดส่งอาหาร'};if(!point)throw new BadRequestException('ต้องระบุพิกัดสำหรับส่งอาหารทันที');const distance=distanceKm(row,point);return {eligible:distance<=row.radius,distanceKm:Math.round(distance*1000)/1000,reason:distance<=row.radius?'อยู่ในโซนจัดส่งอาหาร':'อยู่นอกโซนจัดส่งอาหาร'};}
}
