import {Inject,Injectable,ForbiddenException,ConflictException,BadRequestException} from '@nestjs/common';
import {randomUUID,createHash} from 'node:crypto';
import {z} from 'zod';
import type {PoolClient} from 'pg';
import {Db} from './db';
import {canManage,type Actor} from './access';
const fields={title:z.string().trim().min(3).max(150),description:z.string().trim().min(10).max(1000),meetingPoint:z.string().trim().min(5).max(500),category:z.enum(['nature','culture','food','craft']),durationHours:z.number().int().min(1).max(168),priceSatang:z.number().int().min(1).max(100000000),active:z.boolean()};
export const tripCreate=z.object(fields).strict();
export const tripEdit=z.object({...fields,version:z.number().int().positive()}).strict();
export const departureCreate=z.object({startsAt:z.iso.datetime({offset:true}),capacity:z.number().int().min(1).max(1000)}).strict();
export const departureState=z.object({version:z.number().int().positive(),active:z.boolean()}).strict();
export const bookingCreate=z.object({departureId:z.uuid(),seats:z.number().int().min(1).max(10),expectedPriceSatang:z.number().int().min(1).max(100000000),contactName:z.string().trim().min(1).max(100),phone:z.string().trim().regex(/^\+?[0-9 ()-]{8,20}$/).refine(s=>s.replace(/\D/g,'').length>=8),requestKey:z.uuid()}).strict();
export const bookingAction=z.object({version:z.number().int().positive(),action:z.enum(['confirm','cancel','reject','complete']),reason:z.string().trim().min(3).max(300)}).strict();
const tripSelect=`SELECT t.id,t.store_id AS "storeId",s.name AS "storeName",p.name_th AS province,t.title,t.description,t.meeting_point AS "meetingPoint",t.category,t.duration_hours AS "durationHours",t.price_satang AS "priceSatang",t.active,t.version,COALESCE((SELECT json_agg(json_build_object('id',d.id,'startsAt',d.starts_at,'capacity',d.capacity,'remaining',d.capacity-d.used,'active',d.active,'version',d.version) ORDER BY d.starts_at) FROM departures d WHERE d.trip_id=t.id AND d.starts_at>now()),'[]') AS departures FROM trips t JOIN stores s ON s.id=t.store_id JOIN subdistricts sub ON sub.id=s.subdistrict_id JOIN provinces p ON p.id=sub.province_id`;
const bookingSelect=`SELECT b.id,b.buyer_id AS "buyerId",b.departure_id AS "departureId",s.name AS "storeName",b.title,b.meeting_point AS "meetingPoint",b.starts_at AS "startsAt",b.unit_price_satang AS "unitPriceSatang",b.seats,b.contact_name AS "contactName",b.phone,b.status,b.version,b.created_at AS "createdAt",COALESCE((SELECT json_agg(json_build_object('status',h.status,'reason',h.reason,'createdAt',h.created_at) ORDER BY h.created_at,h.id) FROM booking_history h WHERE h.booking_id=b.id),'[]') AS history FROM bookings b JOIN departures d ON d.id=b.departure_id JOIN trips t ON t.id=d.trip_id JOIN stores s ON s.id=t.store_id JOIN subdistricts sub ON sub.id=s.subdistrict_id`;
const scope="($1='SUPER_ADMIN' OR ($1='ADMIN' AND sub.province_id=ANY($2::text[])) OR ($1='MERCHANT' AND s.id=ANY($3::uuid[])))";
@Injectable() export class Trips {
 constructor(@Inject(Db) private readonly db:Db){}
 private async shop(c:PoolClient,id:string){const s=(await c.query('SELECT s.*,sub.province_id AS "provinceId" FROM stores s JOIN subdistricts sub ON sub.id=s.subdistrict_id WHERE s.id=$1 FOR UPDATE OF s',[id])).rows[0];if(!s)throw new ForbiddenException();return s;}
 private async managedTrip(c:PoolClient,a:Actor,id:string){const ref=(await c.query('SELECT store_id FROM trips WHERE id=$1',[id])).rows[0];if(!ref)throw new ForbiddenException();const s=await this.shop(c,ref.store_id);if(!canManage(a,s))throw new ForbiddenException();return (await c.query('SELECT * FROM trips WHERE id=$1 FOR UPDATE',[id])).rows[0];}
 async catalog(){const rows=(await this.db.pool.query(tripSelect+" WHERE t.active AND s.active AND EXISTS(SELECT 1 FROM departures d WHERE d.trip_id=t.id AND d.active AND d.starts_at>now()) ORDER BY t.created_at DESC LIMIT 100")).rows;return rows.map(t=>({...t,departures:t.departures.filter((d:any)=>d.active)}));}
 async manage(a:Actor){if(a.role==='USER')throw new ForbiddenException();return (await this.db.pool.query(tripSelect+' WHERE '+scope+' ORDER BY t.created_at DESC LIMIT 100',[a.role,a.provinceIds,a.storeIds])).rows;}
 async create(a:Actor,id:string,v:z.infer<typeof tripCreate>){return this.db.transaction(async c=>{const s=await this.shop(c,id);if(!canManage(a,s))throw new ForbiddenException();const tripId=randomUUID();await c.query('INSERT INTO trips(id,store_id,title,description,meeting_point,category,duration_hours,price_satang,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[tripId,id,v.title,v.description,v.meetingPoint,v.category,v.durationHours,v.priceSatang,v.active]);return {id:tripId};});}
 async edit(a:Actor,id:string,v:z.infer<typeof tripEdit>){return this.db.transaction(async c=>{const t=await this.managedTrip(c,a,id);if(t.version!==v.version)throw new ConflictException('ข้อมูลเปลี่ยนแล้ว กรุณาโหลดใหม่');await c.query('UPDATE trips SET title=$1,description=$2,meeting_point=$3,category=$4,duration_hours=$5,price_satang=$6,active=$7,version=version+1 WHERE id=$8',[v.title,v.description,v.meetingPoint,v.category,v.durationHours,v.priceSatang,v.active,id]);return {id};});}
 async departure(a:Actor,id:string,v:z.infer<typeof departureCreate>){return this.db.transaction(async c=>{await this.managedTrip(c,a,id);if(new Date(v.startsAt).getTime()<=Date.now()+3600000)throw new BadRequestException('เปิดรอบล่วงหน้าอย่างน้อย 1 ชั่วโมง');const departureId=randomUUID();const result=await c.query('INSERT INTO departures(id,trip_id,starts_at,capacity) VALUES($1,$2,$3,$4) ON CONFLICT(trip_id,starts_at) DO NOTHING RETURNING id',[departureId,id,v.startsAt,v.capacity]);if(!result.rowCount)throw new ConflictException('มีรอบเวลานี้แล้ว');return {id:departureId};});}
 async departureState(a:Actor,id:string,v:z.infer<typeof departureState>){return this.db.transaction(async c=>{const ref=(await c.query('SELECT trip_id FROM departures WHERE id=$1',[id])).rows[0];if(!ref)throw new ForbiddenException();await this.managedTrip(c,a,ref.trip_id);const d=(await c.query('SELECT * FROM departures WHERE id=$1 FOR UPDATE',[id])).rows[0];if(d.version!==v.version)throw new ConflictException('รอบเปลี่ยนแล้ว กรุณาโหลดใหม่');if(d.starts_at<=new Date())throw new ConflictException('รอบเริ่มแล้ว');await c.query('UPDATE departures SET active=$1,version=version+1 WHERE id=$2',[v.active,id]);return {id};});}
 async bookings(a:Actor,manage:boolean){if(manage&&a.role==='USER')throw new ForbiddenException();return (await this.db.pool.query(bookingSelect+' WHERE '+(manage?scope:'b.buyer_id=$1')+' ORDER BY b.created_at DESC LIMIT 100',manage?[a.role,a.provinceIds,a.storeIds]:[a.id])).rows;}
 async book(a:Actor,v:z.infer<typeof bookingCreate>){return this.db.transaction(async c=>{const hash=createHash('sha256').update(JSON.stringify(v)).digest('hex');await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['booking:'+a.id+':'+v.requestKey]);const old=(await c.query('SELECT id,request_hash FROM bookings WHERE buyer_id=$1 AND request_key=$2',[a.id,v.requestKey])).rows[0];if(old){if(old.request_hash!==hash)throw new ConflictException('รหัสรายการเดิมมีข้อมูลอื่นแล้ว');return {id:old.id};}const ref=(await c.query('SELECT t.store_id,t.id FROM departures d JOIN trips t ON t.id=d.trip_id WHERE d.id=$1',[v.departureId])).rows[0];if(!ref)throw new BadRequestException('ไม่พบรอบ');const s=await this.shop(c,ref.store_id);const t=(await c.query('SELECT * FROM trips WHERE id=$1 FOR UPDATE',[ref.id])).rows[0];const d=(await c.query('SELECT * FROM departures WHERE id=$1 FOR UPDATE',[v.departureId])).rows[0];if(!s.active||!t.active||!d.active||d.starts_at<=new Date())throw new ConflictException('รอบนี้ปิดรับจองแล้ว');if(d.capacity-d.used<v.seats)throw new ConflictException('ที่นั่งไม่พอ กรุณาเลือกรอบหรือจำนวนใหม่');if(t.price_satang!==v.expectedPriceSatang)throw new ConflictException('ราคาเปลี่ยน กรุณาโหลดใหม่');const id=randomUUID();await c.query('INSERT INTO bookings(id,buyer_id,departure_id,request_key,request_hash,seats,title,meeting_point,starts_at,unit_price_satang,contact_name,phone) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)',[id,a.id,d.id,v.requestKey,hash,v.seats,t.title,t.meeting_point,d.starts_at,t.price_satang,v.contactName,v.phone]);await c.query('UPDATE departures SET used=used+$1,version=version+1 WHERE id=$2',[v.seats,d.id]);await c.query("INSERT INTO booking_history VALUES($1,$2,$3,'pending','ผู้เดินทางส่งคำขอจอง',now())",[randomUUID(),id,a.id]);return {id};});}
 async action(a:Actor,id:string,v:z.infer<typeof bookingAction>){return this.db.transaction(async c=>{const ref=(await c.query('SELECT t.store_id FROM bookings b JOIN departures d ON d.id=b.departure_id JOIN trips t ON t.id=d.trip_id WHERE b.id=$1',[id])).rows[0];if(!ref)throw new ForbiddenException();const s=await this.shop(c,ref.store_id);const b=(await c.query('SELECT * FROM bookings WHERE id=$1 FOR UPDATE',[id])).rows[0];if(v.action==='cancel'?b.buyer_id!==a.id:!canManage(a,s))throw new ForbiddenException();if(b.version!==v.version)throw new ConflictException('รายการเปลี่ยนแล้ว กรุณาโหลดใหม่');const future=b.starts_at>new Date();const allowed=v.action==='complete'?b.status==='confirmed'&&!future:v.action==='reject'?['pending','confirmed'].includes(b.status)&&future:b.status==='pending'&&future;if(!allowed)throw new ConflictException('ไม่สามารถเปลี่ยนสถานะนี้ได้');const status={confirm:'confirmed',complete:'completed',cancel:'cancelled',reject:'rejected'}[v.action];if(['cancel','reject'].includes(v.action))await c.query('UPDATE departures SET used=used-$1,version=version+1 WHERE id=$2',[b.seats,b.departure_id]);await c.query('UPDATE bookings SET status=$1,version=version+1 WHERE id=$2',[status,id]);await c.query('INSERT INTO booking_history VALUES($1,$2,$3,$4,$5,now())',[randomUUID(),id,a.id,status,v.reason]);return {id};});}
}
